In [1]:
pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 194.9 kB/s eta 0:01:02
   - -------------------------------------- 0.5/12.6 MB 194.9 kB/s eta 0:01:02
   - -------------------------------------- 0.5/12.6 MB 194.9 kB/s eta 0:01:02
   - -------------------------------------- 0.5/12.6 MB 194.9 kB/s eta 0:01:02
   - -------------------------------------- 0.5/12.6 M

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,])
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr = np.array(42)
print(arr)

42


In [7]:
arr = np.array([[1,2,3,4,],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [3]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

[2 3 4 5]


In [5]:
print(arr[4:])

[5 6 7 8]


In [6]:
print(arr[:4])

[1 2 3 4]


In [7]:
print(arr[-3:-1])

[6 7]


In [8]:
print(arr[1:5:2])

[2 4]


In [9]:
print(arr[::2])

[1 3 5 7]


In [13]:
print(arr[::2])

[1 3 5 7]


In [14]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [19]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [20]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
